language: "python"

python:
  - "3.9"

install:
  - pip install pytest-cov
  - pip install coveralls

script:
  - py.test -vv exercises.py --cov exercises

after_success:
  - coveralls

notifications:
  email: false
